# Generated by Django 4.2.5 on 2023-11-27 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='discord_id',
            field=models.CharField(max_length=18, primary_key=True, serialize=False, unique=True, verbose_name='Unique identifier for Discord user'),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='onboarding_channel_id',
            field=models.CharField(max_length=18, unique=True, verbose_name='ID of the private Discord channel for onboarding'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_file', models.FileField(upload_to='', verbose_name='Store the uploaded receipt')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Amount paid')),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False, verbose_name='Status of payment verification')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.discorduser')),
            ],
        ),
    ]
