# Generated by Django 4.2.5 on 2024-01-03 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('accounts', '0002_alter_bitcampuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcampuser',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='bitcampuser',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='bitcampuser',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('enrollment_date', models.DateField(auto_now=True)),
                ('enrollment_cancel_date', models.DateField(default=None, null=True)),
                ('status', models.CharField(max_length=16)),
                ('mentor_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.mentor')),
                ('program_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.program')),
                ('service_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.service')),
                ('user_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
