# Generated by Django 5.0.1 on 2024-01-15 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_payment_created_at_payment_updated_at'),
        ('content', '0002_service_payze_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='mentor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='content.mentor'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='program_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='content.program'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='service_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='content.service'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
    ]
