# Generated by Django 5.0.3 on 2024-04-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_kidsprofile_delete_discorduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcampuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
