# Generated by Django 5.0.4 on 2024-04-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_authverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='authverificationcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
