# Generated by Django 4.2.5 on 2023-12-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=32)),
                ('biography', models.CharField(blank=True, max_length=256, null=True, verbose_name='Information about the mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Service title')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price of service')),
                ('mentors', models.ManyToManyField(blank=True, to='content.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Program title')),
                ('services', models.ManyToManyField(to='content.service', verbose_name='Program services')),
            ],
        ),
    ]
